[unix_http_server]
file=/var/run/supervisord.sock
chmod=0700

[supervisord]
nodaemon=true
user=root
logfile=/app/logs/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/var/run/supervisord.pid
childlogdir=/app/logs

[program:redis]
command=redis-server --daemonize no
autostart=true
autorestart=true
stdout_logfile=/app/logs/redis.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
stderr_logfile=/app/logs/redis_error.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10

[program:celery]
command=celery -A tasks.executor worker --loglevel=info --pool=solo
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/celery.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
stderr_logfile=/app/logs/celery_error.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10
stopwaitsecs=60

[program:app]
command=uvicorn app:app --host 0.0.0.0 --port 8000
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/app.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
stderr_logfile=/app/logs/app_error.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisord.sock